apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-petclinic-kind
  name: spring-petclinic-kind
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-petclinic-kind
  sessionAffinity: None
  type: LoadBalancer